export { default as Dashboard } from "./Admin/Dashboard";
export { default as Product } from "./Admin/Product";
export { default as Order } from "./Admin/Order";
export { default as AllProduct } from "./Admin/Product/All";
export { default as NewProduct } from "./Admin/Product/New";
export { default as RoleManagement } from "./Admin/UserManagement/Role";
export { default as RoleCreate } from "./Admin/UserManagement/Role/create";
export { default as RoleEdit } from "./Admin/UserManagement/Role/edit";
export { default as UserManagement } from "./Admin/UserManagement/User";
